version: '3'
services:
  reporter:
    expose:
      - 8080
    build:
      context: ./
    ports:
      - ${APP_PORT}:8080
    restart: always

  amqp:
    image: rabbitmq:3.9-management
    expose:
      - 5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PWD}
    restart: always
