version: '3'
services:
  reporter:
    build:
      context: ./
    ports:
      - ${APP_PORT}:8080
    restart: always
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PWD=${RABBITMQ_PWD}
      - RABBITMQ_HOST=amqp
      - RABBITMQ_PORT=5672
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - INTERNAL_PORT=8080
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=db
      - POSTGRES_DB=crashes

  amqp:
    image: rabbitmq:3.9-management
    expose:
      - 5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PWD}
    restart: always

  db:
    image: postgres:12.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=crashes
    volumes:
      - pgdb_data_prod:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:7.3
    depends_on:
      - db
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:postgresql://db/crashes -user=${POSTGRES_USER} -password=${POSTGRES_PWD} -connectRetries=60 migrate

volumes:
  pgdb_data_prod:
    driver: local
